name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Check if colors.rs exists
        id: check_colors
        run: |
          if [ -f "generated/colors.rs" ]; then
            echo "colors_exists=true" >> $GITHUB_OUTPUT
          else
            echo "colors_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate colors.rs if needed
        if: steps.check_colors.outputs.colors_exists == 'false'
        run: |
          echo "Generating colors.rs file..."
          PIGMENT_REGEN=1 cargo build
      
      - name: Run tests
        run: cargo test --all-features
      
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
